version: '3.9'

services:
  watchlist-db:
    container_name: watchlist-db
    image: surrealdb/surrealdb:v1.2.1
    user: root  # DEFINED AS ROOT BECAUSE THE NORMAL USER HAS NO PERMISSION TO STORE DATA.
    command: start file:/data --auth --user $DATABASE_USER --pass $DATABASE_PASS --log $DATABASE_LOG
    ports:
      - 8000:8000/tcp
    volumes:
      - ./data:/data:rw
  # watchlist-api:
  #   container_name: watchlist-api
  #   build: ./api
  #   ports:
  #     - 3000:3000/tcp
