name: Docker Hub

on:
  push:
    branches: [master]

jobs:
  api-docker-publish:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        run: cd api; docker build -t ${{ secrets.DOCKER_REPO }}:latest .;

      - name: Login into Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Push image to docker hub
        run: docker push ${{ secrets.DOCKER_REPO }}:latest
